# Generated by Django 3.2 on 2025-06-25 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventariobodega',
            options={'verbose_name': 'Inventario de Bodega', 'verbose_name_plural': 'Inventarios de Bodega'},
        ),
        migrations.AlterField(
            model_name='inventariobodega',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega'),
        ),
        migrations.AlterField(
            model_name='inventariobodega',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
    ]
