# Generated by Django 3.2 on 2025-06-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20250624_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventariobodega',
            options={'verbose_name': 'Inventario por Bodega', 'verbose_name_plural': 'Inventarios por Bodega'},
        ),
        migrations.AddField(
            model_name='inventariobodega',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
