# Generated by Django 3.2 on 2025-06-25 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20250624_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventariobodega',
            options={},
        ),
        migrations.RemoveField(
            model_name='inventariobodega',
            name='fecha_actualizacion',
        ),
        migrations.AlterField(
            model_name='inventariobodega',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.bodega'),
        ),
        migrations.AlterField(
            model_name='inventariobodega',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto'),
        ),
    ]
